name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update package list
      run: sudo apt-get update
    - name: Install fuse
      run: sudo apt-get install -y libfuse3-dev
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
    - name: Checkout repository
      uses: actions/checkout@v2.4.0
    - name: Install cargo-appimage
      run: cargo install --version 1.4.0 cargo-appimage
    - name: Run cargo build
      run: cargo build --release
      working-directory: atlas-bin
    - name: Run cargo appimage
      run: cargo appimage
      working-directory: atlas-bin
    - uses: actions/upload-artifact@v3
      with:
        name: Atlas Binary
        path: target/release/atlas-bin
